name: Cypress Tests
on:
  pull_request:
    branches:
      - workflow

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.116-1-ff-132.0.1-edge-130.0.2849.68-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: node runner-electron.js