name: k6 Load Test

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by K6 command line

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        
      - name: Run All k6 Tests
        run: |
          k6 run carga.js
          k6 run performance.js
          k6 run stress.js
          
