name: k6 Load Test

on:
  workflow_dispatch:
    inputs:
      cli:
        description: "Run by K6 command line"
        required: false
        default: "k6 run k6/tests/carga.js"

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Verify K6 Installation
        run: k6 version  # Verifica se o K6 foi instalado corretamente

      - name: Run K6 Load Tests
        run: |
          echo "Verificando se os arquivos existem antes de rodar os testes..."
          for file in k6/tests/carga.js k6/tests/performance.js k6/tests/stress.js; do
            if [ -f "$file" ]; then
              echo "Executando $file..."
              k6 run $file
            else
              echo "⚠️ Arquivo $file não encontrado. Pulando este teste."
            fi
          done
